
global:
  jfb:
    namespace: jonathan-mariadb

    volume:
      db:
        type: nfs 
        path: /jfbcore_msa/jf-db
        server: 192.168.1.23

    settings:
      db:
        host: 'jfb-mariadb-galera'
        port: '3306'
        password: 'acryl4958@'
        nodePort: 30033

    name:
      db: mairadb-single