apiVersion: v1
kind: Service
metadata:
  name: jfb-registry-svc
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "acryl-some-key"
spec:
  selector:
    app: jfb-registry
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}