# Default values for storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

system:
  namespace:
  registry:
  imagePullSecrets:
    enabled: 
  privateRepo:
    enabled: 
  privatePip:
    enabled: 
  storage:
    accessMode:

workspace:
  id:
  name:
  namespace:
  # data_storage:
  #   storageClassName:
  #   requests:
  #     storage:
  # main_storage:
  #   storageClassName:
  #   requests:
  #     storage:
  pathPattern:
   
quota:
  memory:
  cpu:
  gpu:

volume:
  # jfData:
  #   type:
  #   path:
  #   server:

  jfBin:
    type: 
    path: 
    server:
