apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.jfb.name.db }}
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  selector:
    app: {{ .Values.global.jfb.name.db }}
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: {{ .Values.global.jfb.settings.db.nodePort }}