apiVersion: v1
kind: PersistentVolume
metadata:
  name: jfb-{{ .Values.global.jfb.namespace }}-mysql-db-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.global.jfb.namespace }}
    name: jfb-mysql-db-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  {{- if eq .Values.global.jfb.volume.db.type "nfs" }}
  nfs:
    server: {{ .Values.global.jfb.volume.db.server }}
    path: {{ .Values.global.jfb.volume.db.path }}
  {{- else if eq .Values.global.jfb.volume.db.type "hostPath" }}
  hostPath:
    path: {{ .Values.global.jfb.volume.db.path }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfb-mysql-db-pvc
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""