namespace: jonathan-system

service:
  type: LoadBalancer          # NodePort, LoadBalancer
  port: 30500
  loadBalancerIP:         # type이 LoadBalancer일때만

volume: # data volume
  type: nfs
  path: /storage/jonathan-storage/jf-data/images
  server: 192.168.0.44

auth:
  enabled: false
  env:
    # auth: htpasswd, token, basic, none
    registryAuth: htpasswd
    registryAuthHtpasswdRealm: "Registry Authentication"
    registryAuthHtpasswdPath: /auth/htpasswd
    registryAuthTokenRealm:
    registryAuthTokenService:
    registryAuthTokenIssuer:
    registryAuthBasicRealm:
    registryAuthHtpasswdPathSubPath: htpasswd
  configMap:
    htpasswd:
      name:

tls:
  enabled: false
  env:
    registryHttpAddr:
    registryHttpTlsCertificate: /tls/registry.crt
    registryHttpTlsKey: /tls/registry.key
  volume:
    registryHttpTlsCertificateSubPath: registry.crt
    registryHttpTlsKeySubPath: registry.key
  configMap:
    cert:
      name: tls-cert
    key:
      name: tls-key

