{{- if .Values.global.jfb.image.pullSecrets.enabled -}}
{{- $fileContent := .Files.Get "file/docker/config" | default "" -}}
{{- if eq $fileContent "" -}}
{{- fail (printf "Error: %s 파일을 넣어주세요" "commonapp/file/docker/config" ) -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.jfb.image.pullSecrets.name }}
  namespace: {{ .Values.global.jfb.namespace }}
data:
  .dockercfg: |-
{{ .Files.Get "file/docker/config" | indent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: {{ .Values.global.jfb.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: {{ .Values.global.jfb.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.global.jfb.namespace }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: patch-sa
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sa
        image: bitnamilegacy/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "kubectl patch serviceaccount default  -n {{ .Values.global.jfb.namespace }} -p '{\"imagePullSecrets\": [{\"name\": \"{{ .Values.global.jfb.image.pullSecrets.name }}\"}]}'"]

{{- end -}}