system:
  namespace:
workspace:
  name:
  id:
  namespace:
  data_storage:
    storageClassName:
    requests:
      storage:
  main_storage:
    storageClassName:
    requests:
      storage:
  # pathPattern: