{{- if .Values.global.jfb.volume.src.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-src-scheduler-pvc
  namespace: {{ .Values.global.jfb.namespace  }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-{{ .Values.global.jfb.namespace }}-src-scheduler-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Values.global.jfb.namespace }}
    name: jf-src-scheduler-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  {{- $srcScheduler := dict -}}
  {{- $_ := set $srcScheduler "src" (deepCopy .Values.global.jfb.volume.src) }}
  {{- $_ := set $srcScheduler.src "path" (printf "%s/%s" .Values.global.jfb.volume.src.path .Values.global.jfb.dir.scheduler) }}
  {{- include "lib.volume.type" $srcScheduler.src | nindent 2 }}
---
{{- end }}