{{- if .Values.global.jfb.volume.front.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.jfb.name.front }}-{{ .Values.global.jfb.namespace }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Values.global.jfb.namespace }}
    name: jf-src-front-pvc
  persistentVolumeReclaimPolicy: Retain
  {{- $srcFront := dict -}}
  {{- $_ := set $srcFront "src" .Values.global.jfb.volume.front }}
  {{- include "lib.volume.type" $srcFront.src | nindent 2 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-src-front-pvc
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end -}}