apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.jfb.name.dataset }}
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.jfb.name.dataset }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.jfb.name.dataset }}
        {{- include "lib.label.jfb" . | nindent 8 }}
      annotations:
        "acryl.ai/appType": system
        checksum/config: {{ include "lib.lookup.settings" . }}
    spec:
      nodeSelector:
      {{- include "lib.nodeSelector.manage" . | nindent 8 }}
      serviceAccountName: {{ .Values.global.jfb.namespace }}-clusteradmin-dataset
      initContainers:
      {{- include "lib.initContainer.db" . | nindent 6}}
      {{- if .Values.global.jfb.image.pullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.jfb.image.pullSecrets.name }}
      {{- end }}
      containers:
      - name: {{ .Values.global.jfb.name.dataset }}
        image: {{ .Values.global.jfb.image.system.registry }}/{{ .Values.global.jfb.image.dataset }}
        imagePullPolicy: {{ .Values.global.jfb.image.pullPolicy }}
        command: [ "/bin/bash", "-c"]
        args: ["cd /app; ./run.sh; sleep infinity;"]
        {{- include "lib.probe.readiness" (dict "app" "dataset" )  | nindent 8 }}
        {{- include "lib.probe.liveness" (dict "app" "dataset" )  | nindent 8 }}
        resources:
          limits:
            cpu : 1
            memory : "1G"
          requests:
            cpu : 0.2
            memory : "256M"
        ports:
        - containerPort: 8000
        env:
        - name: JFB_DATASET_IMAGE
          value: {{ .Values.global.jfb.image.system.registry }}/{{ .Values.global.jfb.image.dataset }}
        - name: FILEBROWSER_IMAGE
          value: {{ .Values.global.jfb.image.system.registry }}/{{ .Values.global.jfb.image.filebrowser }}
        envFrom:
        - configMapRef:
            name: jfb-settings
        volumeMounts:
        {{- include "lib.volume.volumeMounts.storage" . | nindent 8 }}
        {{- include "lib.volume.volumeMounts" (dict "name" "jf-kube" )  | nindent 8 }}
        {{- include "lib.volume.volumeMounts" (dict "name" "jf-src" "enabled" .Values.global.jfb.volume.src.enabled ) | nindent 8 }}
      volumes:
      {{- include "lib.volume.claim" (dict "name" "jf-kube")  | nindent 6 }}
      {{- include "lib.volume.claim" (dict "name" "jf-src" "app" "dataset" "enabled" .Values.global.jfb.volume.src.enabled ) | nindent 6 }}
      {{- include "lib.volume.claim.storage" . | nindent 6  }}
