apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.jfb.name.option }}
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.jfb.name.option }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.jfb.name.option }}
        {{- include "lib.label.jfb" . | nindent 8 }}
      annotations:
        "acryl.ai/appType": system
    spec:
      nodeSelector:
      {{- include "lib.nodeSelector.manage" . | nindent 8 }}
      containers:
      - name: {{ .Values.global.jfb.name.option }}
        image:  {{ .Values.global.jfb.image.system.registry }}/{{ .Values.global.jfb.image.option }}
        imagePullPolicy: {{ .Values.global.jfb.image.pullPolicy }}
        command: [ "/bin/bash", "-c",]
        args: ["cd /app; ./run.sh; sleep infinity;"]
        resources:
          limits:
            cpu : 0.5
            memory : "512M"
          requests:
            cpu : 0.2
            memory : "256M"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: jfb-settings
        volumeMounts:
        {{- include "lib.volume.volumeMounts"  (dict "name" "jf-src" "enabled" .Values.global.jfb.volume.src.enabled )  | nindent 8 }}
        {{- include "lib.volume.volumeMounts.storage" . | nindent 8 }}
      volumes:
      {{- include "lib.volume.claim"  (dict "name" "jf-src" "app" "option" "enabled" .Values.global.jfb.volume.src.enabled )  | nindent 6 }}
      {{- include "lib.volume.claim.storage" . | nindent 6  }}

