apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.jfb.name.playground }}
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.jfb.name.playground }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.jfb.name.playground }}
        {{- include "lib.label.jfb" . | nindent 8 }}
      annotations:
        "acryl.ai/appType": system
    spec:
      serviceAccountName: jfb-playground-sa
      containers:
      - name: {{ .Values.global.jfb.name.playground }}
        image:  {{ .Values.global.jfb.image.system.registry }}/{{ .Values.global.jfb.image.playground }}
        imagePullPolicy: {{ .Values.global.jfb.image.pullPolicy }}
        command: [ "/bin/bash", "-c",]
        args: ["cd /app; ./run.sh; sleep infinity;"]
        resources:
          limits:
            cpu : 0.5
            memory : "256M"
          requests:
            cpu : 0.1
            memory : "128M"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: jfb-settings
        volumeMounts:
        {{- include "lib.volume.volumeMounts"  (dict "name" "jf-src" "enabled" .Values.global.jfb.volume.src.enabled )  | nindent 8 }}
        {{- include "lib.volume.volumeMounts.storage" . | nindent 8 }}
      volumes:
      {{- include "lib.volume.claim"  (dict "name" "jf-src" "app" "playground" "enabled" .Values.global.jfb.volume.src.enabled )  | nindent 6 }}
      {{- include "lib.volume.claim.storage" . | nindent 6  }}



{{/*
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.jfb.name.playground }}
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.jfb.name.playground }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.jfb.name.playground }}
        {{- include "lib.label.jfb" . | nindent 8 }}
      annotations:
        "acryl.ai/appType": system
        checksum/config: {{ include "lib.lookup.settings" . }}
    spec:
      nodeSelector:
      {{- include "lib.nodeSelector.manage" . | nindent 8 }}
      {{- if .Values.global.jfb.image.pullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.jfb.image.pullSecrets.name }}
      {{- end }}
      initContainers:
      {{- include "lib.initContainer.db" . | nindent 6}}
      containers:
      - name: {{ .Values.global.jfb.name.playground }}
        image:  {{ .Values.global.jfb.image.system.registry }}/{{ .Values.global.jfb.image.playground }}
        imagePullPolicy: {{ .Values.global.jfb.image.pullPolicy }}
        command: [ "/bin/bash", "-c",]
        args: ["cd /app; ./run.sh; sleep infinity;"]
        {{- include "lib.probe.readiness" (dict "app" "workspace" )  | nindent 8 }}
        {{- include "lib.probe.liveness" (dict "app" "workspace" )  | nindent 8 }}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: jfb-settings
        livenessProbe:
          httpGet:
            path: api/workspaces
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 180
*/}}

