apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: {{ .Values.global.jfb.name.model }}-api
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  ingressClassName: {{ .Values.global.jfb.settings.external.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Values.global.jfb.name.model }}-svc
            port:
              number: 80
        path: /api/(models)(.*)
        pathType: Prefix