# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#   name:
#   namespace: 
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pvc-b337b370-97d1-4f10-ad87-b6ca603de599
#   resourceVersion: "7198806"
#   uid: 7c3a242f-185d-418b-a7a6-ecc2b503e2f1
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 8Gi
#   claimRef:
#     apiVersion: v1
#     kind: PersistentVolumeClaim
#     name: data-kafka-broker-0
#     namespace: kafka
#     resourceVersion: "7198799"
#     uid: b337b370-97d1-4f10-ad87-b6ca603de599
#   nfs:
#     path: /home/klod/kafka/data
#     server: 192.168.1.16
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: kafka
#   volumeMode: Filesystem
