{{- if .Values.global.jfb.volume.src.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-src-user-pvc
  namespace: {{ .Values.global.jfb.namespace  }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-{{ .Values.global.jfb.namespace }}-src-user-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Values.global.jfb.namespace }}
    name: jf-src-user-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  {{- $srcUser := dict -}}
  {{- $_ := set $srcUser "src" (deepCopy .Values.global.jfb.volume.src) }}
  {{- $_ := set $srcUser.src "path" (printf "%s/%s" .Values.global.jfb.volume.src.path .Values.global.jfb.dir.user) }}
  {{- include "lib.volume.type" $srcUser.src | nindent 2 }}
---
{{- end }}