# selectors, labels, limitsëŠ” dict format 
system:
  namespace:

metadata:
  id:
    workspaceId:
  name:
    podName: "deployment-pod"
    podhHostname: "deployment-pod"
    podBaseName:
    workspaceName:
    trainingName:
    deploymentName:
  namespace:
    systemNamespace:

privateRepo: false
privatePip: false
nexusPrefix: "nexus"
offlineMode: false
nexus:
  hostname: "nexus-nexus-repository-manager.jonathan-nexus.svc.cluster.local"
  port: 8081

pod:
  cpuInstance:
  image:
  imgaeRegistry:

command:
  runCode:
  deploymentWorkerId:

resources:
  limits:
    cpu:
    memory:
    gpu:
    npu:
  requests:
    cpu:
    memory:
    gpu:
    npu:
    
labels:
  deployment_type: 
  deployment_name: 
  deployment_id: 
  deployment_worker_id:  
  workspace_id: 
  workspace_name: 
  instance_id: 
  pod_name: 
  helm_name: 
  user: 

annotations:

env:

cluster:


deployment:
  model_type:
  huggingface_model_id:
  huggingface_token:
  training_id:


