metadata:
  id:
    deploymentId:
    workspaceId:
  name:
    podBaseName:
    workspaceName:
  namespace:
    systemNamespace:

ingress:
  ingressClassName: 

labels:
  deployment_type: 
  work_func_type: 
  deployment_name: 
  deployment_id: 
  deployment_worker_id:  
  workspace_id: 
  workspace_name: 
  instance_id: 
  pod_name: 
  helm_name: 
  user: 