# !JONATHAN 으로 검색 -> 필수 입력
global:
  jfb:
    namespace: jonathan-system # jfb
    volume:
      jfData: # 사용하는 곳: image
        type: nfs # !JONATHAN # nfs, hostpath
        path: /storage/jf-storage/jf-data
        server: 192.168.0.40

      jfBin:
        type: nfs # nfs, hostpath
        path: /storage/jf-storage/jf-bin # /jfbcore_msa/jf-bin
        server: 192.168.0.40

      jfStorage:
        #storage_start
        - type: "nfs"
          name: "local-nfs"
          path: /storage/jf-storage/tmp-storage
          server: 192.168.0.40
        #storage_end

      markerData: # 사용하는 곳: image
        type: nfs 
        path: /storage/jf-storagejf-data
        server: 192.168.0.40

      src:
        enabled: true # true, false (배포일 경우 false)
        type: nfs # nfs
        path: /jp/apps
        server: 192.168.0.40

      front:
        enabled: false # 개발시 src 마운트 경로 위한 볼륨
        # enabled: true 일 경우 작성
        type: # 개발시 nfs로 설정하면 코드반영 바로 안됨, hostPath 권장
        path: # type: hostPath, nfs 일때 작성
        # type: hostPath 일때 작성
        hostname:
        # type: nfs 일때 작성
        server: 192.168.0.97

    settings:
      nexus:
        hostname: "nexus-nexus-repository-manager.jonathan-nexus.svc.cluster.local"
        port: 8081
        enabled: true
        prefix: "nexus"
      db:
        namespace: "jonathan-mariadb" # 없으면 global namespace 사용
        svc: "mariadb-galera"
        port: "3306"
      external:
        protocol: "http"
        host: "115.71.36.57" # !JONATHAN
        port: "80"
        sshPort: "30022"
        redirect: "true" # true -> host , false -> host:port
        ingressClassName: jonathan-kong
      initRootPassword: "tangol1234!"
      redis:
        namespace: "jonathan-redis" # 없으면 global namespace 사용
        clusterEnabled: "true"
        clusterDns: "redis-cluster"
        clusterHeadlessDns: "redis-cluster-headless"
        masterDns: "redis-master"
        slaveDns: "redis-replicas"
      kong:
        namespace: "jonathan-kong"
        adminDns: "kong-kong-admin"
        proxyDns: "kong-kong-proxy"
      kafka:
        namespace: "jonathan-kafka" # 없으면 global namespace 사용
        dns: "kafka"
        # 보안 설정
        protocol: "SASL_PLAINTEXT"
        sasl_mechanism: "PLAIN"
        sasl_username: "tango"
        sasl_password: "tango1234@"
      monitoring:
        node_exporter: "9100"
        namespace: # 없으면 global namespace 사용 (appUrl은 적용 X)
        url: monitoring-kube-prometheus-prometheus
      mongoDb:
        user: "root"
        password: "tango1234@"
        port: "27017"
        namespace: "jonathan-mongodb" # 없으면 global namespace 사용
        dns: "mongodb-headless"
      computing:
        cpu: 0.8 # float
        ram: 0.8 # float
      log:
        name: log-middleware-rest
        namespace: "jonathan-efk" # 없으면 global namespace 사용
        port: "8080"
        protocol: "http"
      filebrowser:
        max: 5
      costManagement:
        enable: "True"
      privateRepo:
        enabled: "false"
      privatePip:
        enabled: "false"

    image:
      runtime: containerd # containerd, docker
      system: # jonathan system API APP registry
        registry: "115.71.28.96:30500" # !JONATHAN
        protocol: https://
      users: # jonathan 유저들이 올리는 이미지
        registry: "192.168.0.40:30500" # !JONATHAN
        protocol: http:// # :// 까지 쓰기
      dataRoot: "/var/lib/containerd"
      pullPolicy: Always # IfNotPresent, Always, Never
      pullSecrets:
        enabled: false
        name: "test" # true 일경우 입력
      front: jfb-system/front:dev
      marker_front: jfb-system/marker_front:dev
      marker_back: jfb-system/marker_back:pdf2image
      marker_db: mariadb:10.11
      dbJob: jfb-system/db:dev
      bin: jfb-system/bin:dev
      user: jfb-system/user_app:dev
      workspace: jfb-system/workspace_app:dev
      dashboard: jfb-system/dashboard_app:dev
      resource: jfb-system/resource_app:dev
      training: jfb-system/training_app:dev
      deployment: jfb-system/deployment_app:dev
      dataset: jfb-system/dataset_app:dev
      image: jfb-system/image_app:dev
      monitoring: jfb-system/monitoring_app:dev
      scheduler: jfb-system/scheduler_app:dev
      notification: jfb-system/notification_app:dev
      cost-management: jfb-system/cost_management_app:0.1.8
      collect: jfb-system/collect_app:dev
      ssh: jfb-system/ssh_app:dev
      db: mariadb:10.11
      storage: jfb-system/storage_app:dev
      playground: jfb-system/playground_app:dev
      rag: jfb-system/rag_app:dev
      model: jfb-system/model_app:dev
      prompt: jfb-system/prompt_app:dev
      pipeline: jfb-system/pipeline_app:dev
      preprocessing: jfb-system/preprocessing_app:dev
      analyzing: jfb-system/analyzing_app:dev
      option: jfb-system/option_app:dev
      filebrowser: jfb-system/filebrowser:0.1.0
      ingress_management: jfb-system/ingress_management_app:dev
      alert_management: jfb-system/alert_management_app:dev
      # kafka_pro: jfb-system/kafka-test_app:dev
      # kafka_consume: jfb-system/kafka-test_app:dev
      # grpc_client: jfb-system/grpc-test_app:dev
      # grpc_server: jfb-system/grpc-test_app:dev

    dir:
      utils: fb_utils
      user: fb_user
      workspace: fb_workspace
      dashboard: fb_dashboard
      resource: fb_resource
      training: fb_training
      deployment: fb_deployment
      dataset: fb_dataset
      image: fb_image
      monitoring: fb_monitoring
      scheduler: fb_scheduler
      notification: fb_notification
      ssh: fb_ssh
      playground: llm_playground
      rag: llm_rag
      model: llm_model
      prompt: llm_prompt
      cost-management: fb_cost_management
      pipeline: fb_pipeline
      preprocessing: fb_preprocessing
      collect: fb_collect
      analyzing: fb_analyzing
      option: fb_option
      ingress_management: fb_ingress_management
      alert_management: fb_alert_management
      # kafka_pro: kafka_producer
      # kafka_consume: kafka_consumer
      # grpc_client: grpc_client
      # grpc_server: grpc_server

    name:
      front: jfb-app-front
      marker_front: marker-app-front
      marker_back: marker-app-back
      marker_db: marker-app-db
      db: jfb-mysql-db
      user: jfb-app-user
      workspace: jfb-app-workspace
      dashboard: jfb-app-dashboard
      resource: jfb-app-resource
      training: jfb-app-training
      deployment: jfb-app-deployment
      dataset: jfb-app-dataset
      image: jfb-app-image
      monitoring: jfb-app-monitoring
      scheduler: jfb-app-scheduler
      notification: jfb-app-notification
      ssh: jfb-app-ssh
      storage: jfb-app-storage
      playground: jfb-llm-playground
      model: jfb-llm-model
      rag: jfb-llm-rag
      prompt: jfb-llm-prompt
      cost-management: jfb-cost-management
      pipeline: jfb-app-pipeline
      preprocessing: jfb-app-preprocessing
      collect: jfb-app-collect
      analyzing: jfb-app-analyzing
      option: jfb-app-option
      ingress_management: jfb-app-ingress-management
      alert_management: jfb-app-alert-management
      # kafka_pro: kafka-pro-app
      # kafka_consume: kafka-consume-app
      # grpc_client: grpc-client-app
      # grpc_server: grpc-server-app

    rdma:
      enabled: false
      mp:
        enabled: false
        seedNum: 3 # 경로를 구분할 시드의 수
        nodeSeedList: []
      perf:
        enabled: false
      # RDMA P2P로 연결된 노드
      p2p: []
