apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.metadata.name.podName }}-src
  namespace: {{ .Values.metadata.namespace.workspaceNamespace }}
data:
  analyzer.py: |-
  {{ .Files.Get "src/analyzer.py" | nindent 4 }}
  db.py: |-
  {{ .Files.Get "src/db.py" | nindent 4 }}
  settings.py: |-
  {{ .Files.Get "src/settings.py" | nindent 4 }}
 