apiVersion: v1
kind: Service
metadata:
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: {{ .Values.service.svc_name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.labels.tool_type }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    index: "0"
  type: ClusterIP